# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build UI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout source repository
        uses: actions/checkout@v3

      # Step 2: Set up your language environment (example: Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm install @clerk/clerk-react
          npm install @clerk/clerk-sdk-node
          npm run build # Adjust based on your project's build script

      # Step 4: Checkout the target branch
      - name: Checkout or create target branch
        run: |
          git fetch origin github-io || true # Fetch target branch if it exists
          git switch github-io || git switch --create github-io # Switch or create branch
          git rm -rf . # Clear existing content from target branch

      # Step 5: Copy compiled files to the target branch
      - name: Copy compiled files
        run: |
          cp -R build/* . # Copy compiled files from build folder to the root

      # Step 6: Commit and push changes to the target branch
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update compiled files from main branch" || echo "No changes to commit"
          git push origin target-branch
